import { useEffect, useRef, useState } from 'react'
import { useFormik } from 'formik'
import * as Yup from 'yup'
import {
  Dialog,
  DialogContent,
  DialogActions,
  Box,
  Typography,
  IconButton,
  Button,
  Divider,
  TextField,
  Checkbox,
  FormControlLabel,
  ToggleButtonGroup,
  ToggleButton,
} from '@mui/material'
import { UserType } from '@/features/users/types'
import { useCreateUser, generatePassword } from '@/features/users/hooks/useCreateUser'
import { checkEmailExists } from '@/features/users/api/checkEmail'
import { XIcon, UsersIcon, UserIcon, ShieldUserIcon, EyeIcon, EyeOffIcon } from '@/components/ui/icons'

const TYPE_OPTIONS: { value: UserType; label: string; icon: React.ReactNode }[] = [
  { value: UserType.USER, label: 'Học viên', icon: <UserIcon className="size-5" /> },
  { value: UserType.TEACHER, label: 'Giảng viên', icon: <UsersIcon className="size-5" /> },
  { value: UserType.ADMIN, label: 'Quản trị', icon: <ShieldUserIcon className="size-5" /> },
]

const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

const schema = Yup.object({
  name: Yup.string().required('Vui lòng nhập họ và tên'),
  email: Yup.string().email('Email không hợp lệ').required('Vui lòng nhập email'),
  type: Yup.mixed<UserType>().oneOf(Object.values(UserType)).required(),
  password: Yup.string().required('Vui lòng nhập mật khẩu'),
  isSendPasswordViaEmail: Yup.boolean().required(),
})

interface CreateUserModalProps {
  onClose: () => void
  onCreated: () => void
}

export function CreateUserModal({ onClose, onCreated }: CreateUserModalProps) {
  const { submit, isLoading, error } = useCreateUser(onCreated)
  const [isAutoGenerated, setIsAutoGenerated] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [isCheckingEmail, setIsCheckingEmail] = useState(false)
  const [emailTakenError, setEmailTakenError] = useState<string | null>(null)
  const hasAutoGeneratedOnce = useRef(false)

  const formik = useFormik({
    initialValues: { name: '', email: '', type: UserType.USER, password: '', isSendPasswordViaEmail: false },
    validationSchema: schema,
    onSubmit: async (values) => {
      await submit(values)
    },
  })

  const emailValue = formik.values.email
  useEffect(() => {
    setEmailTakenError(null)
    if (!EMAIL_REGEX.test(emailValue)) return

    setIsCheckingEmail(true)
    const timer = setTimeout(async () => {
      try {
        const exists = await checkEmailExists(emailValue)
        setEmailTakenError(exists ? 'Email này đã được sử dụng' : null)
      } catch {
        // silently ignore check errors
      } finally {
        setIsCheckingEmail(false)
      }
    }, 500)

    return () => clearTimeout(timer)
  }, [emailValue])

  function handlePasswordFocus() {
    if (!hasAutoGeneratedOnce.current && !formik.values.password) {
      const pwd = generatePassword()
      formik.setFieldValue('password', pwd)
      setIsAutoGenerated(true)
      setShowPassword(true)
      hasAutoGeneratedOnce.current = true
    }
  }

  function handlePasswordChange(e: React.ChangeEvent<HTMLInputElement>) {
    setIsAutoGenerated(false)
    setShowPassword(false)
    formik.handleChange(e)
  }

  function handlePasswordBlur(e: React.FocusEvent<HTMLInputElement>) {
    if (isAutoGenerated) setShowPassword(false)
    formik.handleBlur(e)
  }

  return (
    <Dialog
      open
      onClose={onClose}
      fullWidth
      slotProps={{ paper: { sx: { borderRadius: '18px', width: 480, maxWidth: '100%' } } }}
    >
      {/* Header */}
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, px: 3, py: 2.5, borderBottom: '1px solid', borderColor: 'divider' }}>
        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', width: 38, height: 38, borderRadius: '10px', bgcolor: '#e7eefe', flexShrink: 0 }}>
          <UsersIcon className="size-5" style={{ color: '#2563eb' }} />
        </Box>
        <Box>
          <Typography sx={{ fontWeight: 700, fontSize: 16.5, color: '#0f1b33' }}>Thêm người dùng</Typography>
          <Typography sx={{ fontSize: 12.5, color: '#6b7686' }}>Tạo tài khoản mới trong hệ thống</Typography>
        </Box>
        <IconButton onClick={onClose} sx={{ ml: 'auto', color: '#9aa4b2' }} size="small">
          <XIcon className="size-[19px]" />
        </IconButton>
      </Box>

      {/* Form */}
      <form id="create-user-form" onSubmit={formik.handleSubmit}>
        <DialogContent sx={{ px: 3, pt: 3, pb: 0 }}>
          <TextField
            label="Họ và tên"
            fullWidth
            size="small"
            placeholder="Nguyễn Văn A"
            {...formik.getFieldProps('name')}
            error={formik.touched.name && !!formik.errors.name}
            helperText={formik.touched.name && formik.errors.name}
            sx={{ mb: 2.75 }}
          />
          <TextField
            label="Email"
            type="email"
            fullWidth
            size="small"
            placeholder="email@ins.edu.vn"
            {...formik.getFieldProps('email')}
            error={(formik.touched.email && !!formik.errors.email) || !!emailTakenError}
            helperText={(formik.touched.email && formik.errors.email) || emailTakenError || (isCheckingEmail ? 'Đang kiểm tra...' : undefined)}
            sx={{ mb: 2.75 }}
          />
          <TextField
            label="Mật khẩu"
            type={showPassword ? 'text' : 'password'}
            fullWidth
            size="small"
            slotProps={{
              htmlInput: { placeholder: 'Nhấp vào để tự động tạo mật khẩu' },
              input: {
                endAdornment: (
                  <IconButton
                    size="small"
                    onClick={() => setShowPassword((v) => !v)}
                    edge="end"
                    sx={{ color: '#9aa4b2' }}
                  >
                    {showPassword ? <EyeOffIcon className="size-[19px]" /> : <EyeIcon className="size-[19px]" />}
                  </IconButton>
                ),
              },
            }}
            {...formik.getFieldProps('password')}
            onChange={handlePasswordChange}
            onFocus={handlePasswordFocus}
            onBlur={handlePasswordBlur}
            error={formik.touched.password && !!formik.errors.password}
            helperText={formik.touched.password && formik.errors.password}
            sx={{ mb: 1.5 }}
          />

          <FormControlLabel
            control={
              <Checkbox
                size="small"
                checked={formik.values.isSendPasswordViaEmail}
                onChange={(e) => formik.setFieldValue('isSendPasswordViaEmail', e.target.checked)}
              />
            }
            label={<span style={{ fontSize: 13.5 }}>Gửi mật khẩu qua email cho người dùng</span>}
            sx={{ mb: 2.75, ml: 0 }}
          />

          {/* Type selector */}
          <Typography sx={{ mb: 1, fontSize: 13, fontWeight: 600, color: '#44505f' }}>
            Loại tài khoản
          </Typography>
          <ToggleButtonGroup
            exclusive
            fullWidth
            value={formik.values.type}
            onChange={(_, v) => v && formik.setFieldValue('type', v)}
            sx={{ mb: 2.75 }}
          >
            {TYPE_OPTIONS.map(({ value, label, icon }) => (
              <ToggleButton
                key={value}
                value={value}
                sx={{
                  flexDirection: 'column',
                  gap: 0.5,
                  py: 1.5,
                  fontSize: 13,
                  fontWeight: 600,
                  borderColor: '#e3e7ee',
                  textTransform: 'none',
                  color: '#6b7686',
                  '&.Mui-selected': {
                    borderColor: 'primary.main',
                    bgcolor: '#f3f7ff',
                    color: 'primary.main',
                  },
                }}
              >
                {icon}
                {label}
              </ToggleButton>
            ))}
          </ToggleButtonGroup>

          {error && (
            <Typography sx={{ mb: 1.5, fontSize: 12.5, color: 'error.main' }}>{error}</Typography>
          )}
        </DialogContent>

        <Divider />
        <DialogActions sx={{ bgcolor: '#f5f7fa', px: 3, py: 2, gap: 1.5 }}>
          <Button
            type="button"
            onClick={onClose}
            variant="outlined"
            sx={{ height: 40, borderRadius: '8px', fontSize: 14, fontWeight: 600, borderColor: '#e3e7ee', color: '#44505f', textTransform: 'none' }}
          >
            Huỷ
          </Button>
          <Button
            type="submit"
            variant="contained"
            disabled={isLoading || isCheckingEmail || !!emailTakenError}
            startIcon={<UsersIcon className="size-[17px]" />}
            sx={{ height: 40, borderRadius: '8px', fontSize: 14, fontWeight: 600, textTransform: 'none' }}
          >
            {isLoading ? 'Đang tạo...' : 'Tạo tài khoản'}
          </Button>
        </DialogActions>
      </form>
    </Dialog>
  )
}
