import { useRef, useState } from 'react'
import { useFormik } from 'formik'
import * as Yup from 'yup'
import { UserType } from '@/features/users/types'
import { useCreateUser, generatePassword } from '@/features/users/hooks/useCreateUser'
import { TextField } from '@/components/ui/TextField'
import { Checkbox } from '@/components/ui/Checkbox'
import { XIcon, UsersIcon, UserIcon, ShieldUserIcon, EyeIcon, EyeOffIcon } from '@/components/ui/icons'
import { cn } from '@/utils/cn'

const TYPE_OPTIONS: { value: UserType; label: string; icon: React.ReactNode }[] = [
  { value: UserType.USER, label: 'Học viên', icon: <UserIcon className="size-5" /> },
  { value: UserType.TEACHER, label: 'Giảng viên', icon: <UsersIcon className="size-5" /> },
  { value: UserType.ADMIN, label: 'Quản trị', icon: <ShieldUserIcon className="size-5" /> },
]

const schema = Yup.object({
  name: Yup.string().required('Vui lòng nhập họ và tên'),
  email: Yup.string().email('Email không hợp lệ').required('Vui lòng nhập email'),
  type: Yup.mixed<UserType>().oneOf(Object.values(UserType)).required(),
  password: Yup.string().required('Vui lòng nhập mật khẩu'),
  isSendPasswordViaEmail: Yup.boolean().required(),
})

interface CreateUserModalProps {
  onClose: () => void
  onCreated: () => void
}

export function CreateUserModal({ onClose, onCreated }: CreateUserModalProps) {
  const { submit, isLoading, error } = useCreateUser(onCreated)
  const [isAutoGenerated, setIsAutoGenerated] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const hasAutoGeneratedOnce = useRef(false)

  const formik = useFormik({
    initialValues: { name: '', email: '', type: UserType.USER, password: '', isSendPasswordViaEmail: false },
    validationSchema: schema,
    onSubmit: async (values) => {
      await submit(values)
    },
  })

  function handlePasswordFocus() {
    if (!hasAutoGeneratedOnce.current && !formik.values.password) {
      const pwd = generatePassword()
      formik.setFieldValue('password', pwd)
      setIsAutoGenerated(true)
      setShowPassword(true)
      hasAutoGeneratedOnce.current = true
    }
  }

  function handlePasswordChange(e: React.ChangeEvent<HTMLInputElement>) {
    setIsAutoGenerated(false)
    setShowPassword(false)
    formik.handleChange(e)
  }

  function handlePasswordBlur(e: React.FocusEvent<HTMLInputElement>) {
    if (isAutoGenerated) setShowPassword(false)
    formik.handleBlur(e)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-[rgba(8,16,28,0.42)] backdrop-blur-[1.5px]" onClick={onClose} />
      <div className="relative w-[480px] overflow-hidden rounded-[18px] bg-white shadow-[0px_12px_32px_-8px_rgba(31,39,51,0.22)]">
        {/* Header */}
        <div className="flex items-center gap-4 border-b border-line px-[22px] py-5">
          <div className="flex size-[38px] items-center justify-center rounded-[10px] bg-ring-soft">
            <UsersIcon className="size-5 text-primary" />
          </div>
          <div>
            <p className="text-[16.5px] font-bold text-ink">Thêm người dùng</p>
            <p className="text-[12.5px] text-muted">Tạo tài khoản mới trong hệ thống</p>
          </div>
          <button onClick={onClose} className="ml-auto text-faint hover:text-label">
            <XIcon className="size-[19px]" />
          </button>
        </div>

        {/* Body */}
        <form onSubmit={formik.handleSubmit} className="px-[22px] pt-[22px]">
          <TextField
            label="Họ và tên"
            placeholder="Nguyễn Văn A"
            {...formik.getFieldProps('name')}
            error={formik.touched.name ? formik.errors.name : undefined}
            className="mb-[22px]"
          />
          <TextField
            label="Email"
            type="email"
            placeholder="email@ins.edu.vn"
            {...formik.getFieldProps('email')}
            error={formik.touched.email ? formik.errors.email : undefined}
            className="mb-[22px]"
          />
          <TextField
            label="Mật khẩu"
            type={showPassword ? 'text' : 'password'}
            placeholder="Nhấp vào để tự động tạo mật khẩu"
            {...formik.getFieldProps('password')}
            onChange={handlePasswordChange}
            onFocus={handlePasswordFocus}
            onBlur={handlePasswordBlur}
            error={formik.touched.password ? formik.errors.password : undefined}
            className="mb-3"
            trailing={
              <button
                type="button"
                onClick={() => setShowPassword((v) => !v)}
                aria-label={showPassword ? 'Ẩn mật khẩu' : 'Hiện mật khẩu'}
                className="shrink-0 cursor-pointer text-faint transition-colors hover:text-label"
              >
                {showPassword ? <EyeOffIcon className="size-4.75" /> : <EyeIcon className="size-4.75" />}
              </button>
            }
          />
          <div className="mb-[22px]">
            <Checkbox
              label="Gửi mật khẩu qua email cho người dùng"
              checked={formik.values.isSendPasswordViaEmail}
              onChange={(e) => formik.setFieldValue('isSendPasswordViaEmail', e.target.checked)}
            />
          </div>

          {/* Type selector */}
          <p className="mb-2 text-[13px] font-semibold text-label">Loại tài khoản</p>
          <div className="mb-[22px] grid grid-cols-3 gap-3">
            {TYPE_OPTIONS.map(({ value, label, icon }) => {
              const selected = formik.values.type === value
              return (
                <button
                  key={value}
                  type="button"
                  onClick={() => formik.setFieldValue('type', value)}
                  className={cn(
                    'flex flex-col items-center gap-1 rounded-[11px] border py-3 transition-colors',
                    selected
                      ? 'border-primary bg-[#f3f7ff] text-primary'
                      : 'border-line bg-white text-muted hover:border-edge',
                  )}
                >
                  {icon}
                  <span className="text-[13px] font-semibold">{label}</span>
                </button>
              )
            })}
          </div>

          {error && <p className="mb-3 text-[12.5px] text-red-600">{error}</p>}

          {/* Footer */}
          <div className="-mx-[22px] flex items-center justify-end gap-3 border-t border-line bg-[#f5f7fa] px-[22px] py-4">
            <button
              type="button"
              onClick={onClose}
              className="h-10 rounded-[8px] border border-line px-5 text-[14px] font-semibold text-label hover:bg-white"
            >
              Huỷ
            </button>
            <button
              type="submit"
              disabled={isLoading}
              className="flex h-10 items-center gap-2 rounded-[8px] bg-primary px-5 text-[14px] font-semibold text-white shadow-[0px_2px_8px_-2px_#2563eb] hover:bg-primary-dark disabled:opacity-60"
            >
              <UsersIcon className="size-[17px]" />
              {isLoading ? 'Đang tạo...' : 'Tạo tài khoản'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
