name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /opt/INS-Classes
            git pull origin master

            cd INS-Classes-BE
            chmod +x gradlew
            ./gradlew bootJar
            systemctl restart ins-classes
            echo "✅ Backend deployed successfully"

            cd ../INS-Classes-FE
            npm install
            npm run build
            systemctl reload nginx
            echo "✅ Frontend deployed successfully"
